"""Add customer columns

Revision ID: 40d442584966
Revises: 
Create Date: 2026-02-09 00:21:16.596403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '40d442584966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('customer', sa.Column('city', sa.String(), nullable=False, server_default=''))
    op.add_column('customer', sa.Column('address', sa.String(), nullable=False, server_default=''))
    op.add_column('customer', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('customer', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('customer', sa.Column('travel_radius', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_customer_location')
    op.create_index('idx_customer_location', 'customer', ['location'], unique=False, postgresql_using='gist')
    op.alter_column('kyc_requests', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'document'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc_requests', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'document'::character varying"))
    op.drop_index('idx_customer_location', table_name='customer', postgresql_using='gist')
    op.drop_column('customer', 'location')
    op.drop_column('customer', 'travel_radius')
    op.drop_column('customer', 'longitude')
    op.drop_column('customer', 'latitude')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'city')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
