"""add_address_fields_to_customer_and_artist

Revision ID: 82aa7982c6ac
Revises: 40d442584966
Create Date: 2026-02-11 19:01:51.581304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82aa7982c6ac'
down_revision: Union[str, None] = '40d442584966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('flat_building', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('street_area', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('landmark', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('state', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('flat_building', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('street_area', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('landmark', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'state')
    op.drop_column('customer', 'pincode')
    op.drop_column('customer', 'landmark')
    op.drop_column('customer', 'street_area')
    op.drop_column('customer', 'flat_building')
    op.drop_column('artists', 'state')
    op.drop_column('artists', 'pincode')
    op.drop_column('artists', 'landmark')
    op.drop_column('artists', 'street_area')
    op.drop_column('artists', 'flat_building')
    # ### end Alembic commands ###
